import React from 'react';
import { TESTIMONIALS } from '../constants';

export const ProofSection: React.FC = () => {
  return (
    <section className="py-16 bg-white overflow-hidden">
      <div className="container mx-auto px-4">
        
        {/* Visual Proof */}
        <div className="flex flex-col md:flex-row items-center gap-12 mb-16">
          <div className="w-full md:w-1/2">
             <div className="relative">
                <img 
                    src="https://images.unsplash.com/photo-1551522435-a13afa10f103?auto=format&fit=crop&q=80&w=800" 
                    alt="Sample PDF Report on Tablet" 
                    className="rounded-xl shadow-2xl border border-gray-200"
                />
                <div className="absolute -bottom-6 -right-6 bg-white p-4 rounded-lg shadow-xl border border-gray-100 hidden md:block">
                    <p className="font-heading font-bold text-trust text-lg">100+ Data Points</p>
                    <p className="text-gray-500 text-sm">Transmission, ABS, SRS, Engine</p>
                </div>
             </div>
          </div>
          <div className="w-full md:w-1/2">
            <h2 className="font-heading text-3xl font-bold mb-4">Professional Reports Emailed Instantly</h2>
            <p className="text-gray-600 text-lg mb-6">
                You don't just get a verbal "it's fine." You get a comprehensive PDF report generated by our $4,000 Autel Ultra scanner.
            </p>
            <ul className="space-y-3">
                <li className="flex items-center text-gray-700">
                    <i className="fa-solid fa-file-pdf text-red-500 mr-3 text-xl"></i>
                    <span>Full System Health Report</span>
                </li>
                <li className="flex items-center text-gray-700">
                    <i className="fa-solid fa-list-check text-primary mr-3 text-xl"></i>
                    <span>Live Data Stream Analysis</span>
                </li>
                <li className="flex items-center text-gray-700">
                    <i className="fa-solid fa-envelope-open-text text-trust mr-3 text-xl"></i>
                    <span>Delivered to Email & Text Immediately</span>
                </li>
            </ul>
          </div>
        </div>

        {/* Reviews */}
        <div className="text-center mb-10">
             <h3 className="font-heading text-2xl font-bold">Trusted by Tampa Bay Drivers</h3>
             <div className="flex justify-center items-center gap-2 mt-2">
                 <div className="flex text-yellow-400">
                     <i className="fa-solid fa-star"></i>
                     <i className="fa-solid fa-star"></i>
                     <i className="fa-solid fa-star"></i>
                     <i className="fa-solid fa-star"></i>
                     <i className="fa-solid fa-star"></i>
                 </div>
                 <span className="font-bold text-gray-700">4.9/5 Average</span>
             </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t) => (
                <div key={t.id} className="bg-gray-50 p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col">
                    <div className="flex text-yellow-400 mb-3 text-sm">
                        {[...Array(t.stars)].map((_, i) => <i key={i} className="fa-solid fa-star"></i>)}
                    </div>
                    <p className="text-gray-600 italic mb-4 flex-grow">"{t.text}"</p>
                    <div className="mt-auto flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-trust text-white flex items-center justify-center font-bold">
                            {t.name.charAt(0)}
                        </div>
                        <div>
                            <p className="font-bold text-gray-900 text-sm">{t.name}</p>
                            <p className="text-xs text-gray-500">{t.role}</p>
                        </div>
                    </div>
                </div>
            ))}
        </div>
        
      </div>
    </section>
  );
};
